# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run: go install ./...
      - run: go test ./...
      - run: go vet ./...
      - run:
          name: "Check the generated files have been commit"
          command: |
            set -euxo pipefail
            go generate ./...
            git diff --quiet --exit-code

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test

